# General settings
title: Business Card theme

background:
  color: rgb(43,42,51)

foreground:
  color: whitesmoke

# Card info
card:
  #name:       John Doe
  #titles:     ""

# Profiles
profiles:
  github: J3-Tech/business-card-jekyll
  youtube: user/YouTube
  twitter: twitter
  instagram: instagram
  facebook: facebook
  linkedin: linkedin
  stackoverflow: 1
  twitch: twitch

# Others
markdown: kramdown
